### ISSUE TITLE
Problems authorizing courseraoauth2client

### ISSUE THREAD

**Issue by rperezalvarez** [coursera/courseraresearchexports#43]
Hello I am trying to authorize con auth2 following the command:

 courseraoauth2client config authorize --app manager_research_exports

but I get this message
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "/home/ronald/anaconda2/envs/snowflakes/lib/python2.7/site-packages/courseraoauth2client/main.py", line 64, in main
    return args.func(args)
  File "/home/ronald/anaconda2/envs/snowflakes/lib/python2.7/site-packages/courseraoauth2client/commands/config.py", line 36, in authorize
    oauth2_instance = oauth2.build_oauth2(args.app, args)
  File "/home/ronald/anaconda2/envs/snowflakes/lib/python2.7/site-packages/courseraoauth2client/oauth2.py", line 472, in build_oauth2
    configure_app(app, cfg)
  File "/home/ronald/anaconda2/envs/snowflakes/lib/python2.7/site-packages/courseraoauth2client/oauth2.py", line 517, in configure_app
    with open(cfg_path, 'wb') as configfile:
IOError: [Errno 2] No such file or directory: '/home/ronald/.coursera/courseraoauth2client.cfg'

Thanks

**Comment by tlee-coursera** [comment]
It looks like there is a problem creating that file for some reason.  Could you try to create the file beforehand with the following command and see if that helps?
`touch /home/ronald/.coursera/courseraoauth2client.cfg`

Also, there was a typo with your command, but it probably wasn't the cause of the issue.
`courseraoauth2client config authorize --app manage_research_exports`

**Comment by rperezalvarez** [comment]
Tranks, I created the file handly before and it work good.
