### ISSUE TITLE
"courseraresearchexports jobs request tables" HTTP error 403

### ISSUE THREAD

**Issue by Stefi-Tirkova** [coursera/courseraresearchexports#61]
Running `courseraresearchexports jobs request tables --course_slug machine-learning --purpose=research` returns the following error message:
```
_ERROR:root:Request to https://www.coursera.org/api/onDemandExports.v2/ with body:
        {"exportType": "RESEARCH_WITH_SCHEMAS", "scope": {"typeName": "courseContext", "definition": {"courseId": "Gtv4Xb1-EeS-ViIACwYKVQ"}}, "statementOfPurpose": "research", "anonymityLevel": "HASHED_IDS_WITH_ISOLATED_UGC_NO_PII", "schemaNames": ["demographics", "users", "course_membership", "course_progress", "feedback", "assessments", "course_grades", "peer_assignments", "discussions", "programming_assignments", "course_content", "ecb", "notebooks", "transactions"]}
received response:
        {"errorCode":"Not Authorized","message":null,"details":null}
Please contact data-support@coursera.org or #data-exports on Slack for assistance
ERROR:root:Problem when running command. Sorry!
Traceback (most recent call last):
  File "c:\dev\python27\lib\site-packages\courseraresearchexports\main.py", line 86, in main
    return args.func(args)
  File "c:\dev\python27\lib\site-packages\courseraresearchexports\commands\jobs.py", line 74, in request_tables
    export_request_with_metadata = api.post(export_request)[0]
  File "c:\dev\python27\lib\site-packages\courseraresearchexports\models\utils.py", line 40, in response_transformer_wrapper
    response.raise_for_status()
  File "c:\dev\python27\lib\site-packages\requests\models.py", line 844, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
HTTPError: 403 Client Error: Forbidden for url: https://www.coursera.org/api/onDemandExports.v2/_
```

**Comment by lcruz-coursera** [comment]
You may need to authorize the application. 

You can do so by running `courseraoauth2client config authorize --app manage_research_exports`

This is a required step in the [setup](https://github.com/coursera/courseraresearchexports#setup)
